#' generate_syn_copula Function: Generates synthetic data using Gaussian copula
#'
#' This function generates synthetic data by modeling the correlation structure of the input dataset using a Gaussian copula.
#' It estimates the copula parameters from the original dataset and uses them to generate new synthetic samples.
#' The generated synthetic data maintains the same correlation structure as the original dataset.
#'
#' @param data_model A list containing the original dataset (`original`), transformed uniform dataset (`data_uniform`), and metadata (`metadata`).
#'                   The metadata should include column names (`col_names`).
#' @param n_samples The number of synthetic samples to generate. If not provided, the function defaults to the number of rows in the original dataset.
#'
#' @return A data frame containing synthetic data with the same structure as the input dataset. The data will have the same column names as the original dataset,
#'         and the correlation structure will match the original dataset's correlation structure.
#'
#' @details
#' - The function computes the correlation matrix of the uniform-transformed data and uses it to create a Gaussian copula.
#' - The copula is fitted to the dataset, and new synthetic samples are generated by sampling from the fitted copula.
#' - The synthetic data is returned in a uniform space, preserving the correlation structure of the original dataset.
#'
#' @examples
#' # Assuming data_model is a list containing the original dataset and metadata
#' @seealso \code{\link{create_model}}
#' synthetic_data <- generate_syn_copula(data_model, n_samples = 1000)
#'
#' @export
generate_syn_copula <- function(data_model, n_samples = NA) {

  if (is.na(n_samples)) n_samples <- NROW(data_model$original)

  # Step 1: Detect constant columns
  is_constant <- apply(data_model$data_uniform, 2, function(col) {
    length(unique(na.omit(col))) == 1
  })

  # Step 2: Remove constant columns temporarily
  data_uniform_reduced <- data_model$data_uniform[, !is_constant, drop = FALSE]

  # Step 3: Fit Gaussian Copula to reduced data
  cor_matrix <- cor(data_uniform_reduced, use = "pairwise.complete.obs")

  # Handle NA or ill-conditioned correlation matrix
  if (anyNA(cor_matrix)) stop("Correlation matrix contains NA values. Check data.")

  gaussian_cop <- copula::normalCopula(
    param = cor_matrix[lower.tri(cor_matrix)],
    dim = ncol(data_uniform_reduced),
    dispstr = "un"
  )

  # Use complete cases only for copula fitting
  complete_data <- na.omit(as.matrix(data_uniform_reduced))
  fit <- copula::fitCopula(gaussian_cop, complete_data)

  # Step 4: Sample synthetic data in uniform space
  synthetic_uniform <- copula::rCopula(n_samples, fit@copula)
  synthetic_uniform <- as.data.frame(synthetic_uniform)
  colnames(synthetic_uniform) <- colnames(data_uniform_reduced)

  # Step 5: Add back constant columns
  const_values <- sapply(data_model$data_uniform[, is_constant, drop = FALSE], function(col) unique(na.omit(col)))
  const_matrix <- as.data.frame(matrix(rep(const_values, each = n_samples), nrow = n_samples))
  colnames(const_matrix) <- names(const_values)

  # Step 6: Combine and restore original column order
  synthetic_uniform_full <- cbind(synthetic_uniform, const_matrix)
  synthetic_uniform_full <- synthetic_uniform_full[, colnames(data_model$data_uniform)]

  return(convert_back_original(synthetic_uniform_full))
}
