#' generate_syn_copula Function: Generates synthetic data using Gaussian copula
#'
#' This function generates synthetic data by modeling the correlation structure of the input dataset using a Gaussian copula.
#' It estimates the copula parameters from the original dataset and uses them to generate new synthetic samples.
#' The generated synthetic data maintains the same correlation structure as the original dataset.
#'
#' @param data_model A list containing the original dataset (`original`), transformed uniform dataset (`data_uniform`), and metadata (`metadata`).
#'                   The metadata should include column names (`col_names`).
#' @param n_samples The number of synthetic samples to generate. If not provided, the function defaults to the number of rows in the original dataset.
#'
#' @return A data frame containing synthetic data with the same structure as the input dataset. The data will have the same column names as the original dataset,
#'         and the correlation structure will match the original dataset's correlation structure.
#'
#' @details
#' - The function computes the correlation matrix of the uniform-transformed data and uses it to create a Gaussian copula.
#' - The copula is fitted to the dataset, and new synthetic samples are generated by sampling from the fitted copula.
#' - The synthetic data is returned in a uniform space, preserving the correlation structure of the original dataset.
#'
#' @examples
#' # Assuming data_model is a list containing the original dataset and metadata
#' @seealso \code{\link{create_model}}
#' synthetic_data <- generate_syn_copula(data_model, n_samples = 1000)
#'
#' @export
generate_syn_copula <- function(data_model, n_samples = NA) {

  if(is.na(n_samples)) n_samples<-NROW(data_model$original)

  # Fit Gaussian Copula Model
  cor_matrix <- cor(data_model$data_uniform, use = "pairwise.complete.obs")
  gaussian_cop <- copula::normalCopula(param = cor_matrix[lower.tri(cor_matrix)],
                                 dim = ncol(data_model$data_uniform),
                                 dispstr = "un")
  fit <- copula::fitCopula(gaussian_cop, as.matrix(data_model$data_uniform))
  synthetic_uniform <- copula::rCopula(n_samples, fit@copula)

  # Convert synthetic data to a data frame
  synthetic_uniform <- as.data.frame(synthetic_uniform)

  # Assign column names to match the input dataset
  colnames(synthetic_uniform) <-  colnames(data_model$data_uniform)

  return(convert_back_original(data_model,synthetic_uniform))
}
